### ISSUE TITLE
Updating base class NO_CATEGORY

### ISSUE THREAD

**Issue by jonpas** [ArmaAchilles/AresModAchillesExpansion#114]
Caused by:
https://github.com/oOKexOo/AresModAchillesExpansion/blob/7e185216026cf0edf856011c9572230b223d6956/%40AresModAchillesExpansion/addons/modules_f_achilles/cfgFactionClasses.hpp#L6

ACE3 Zeus sets it as:
https://github.com/acemod/ACE3/blob/master/addons/zeus/CfgFactionClasses.hpp#L12

Achilles class should be renamed to something different. Also your classes should **really** be prefixed.

**Comment by oOKexOo** [comment]
I suspect that I created that inheritance, since the vanilla factions inherit from NO_CATEGORY as well.
I agree they should be prefixed.

**Comment by jonpas** [comment]
Yeah, it would all be fine if you wouldn't use the exact same name for the class as ACE3 does, that's exactly what prefixing solve. :)

**Comment by oOKexOo** [comment]
It's actually intentional that the very same class is used as in ACE, because the modules in that category are primarely designed for ACE.
The other moduels with no prefixes are prefixed in dev branch.

**Comment by jonpas** [comment]
Why is it intentional though? There is absolutely no reason to use the `ace_` prefix for your own modules, all you are asking for is trouble. And with what you are doing you are basically overwriting a class. Hmh, honestly you are not doing anything with the class, just setting the same property as is already set?

**Comment by oOKexOo** [comment]
The idea is to use the very same category, but without creating a dependency on ACE. That's why there is a duplicate in Achilles. Otherwise you would have two "ACE Medical" categories in the module tree.

**Comment by jonpas** [comment]
@oOKexOo I have apparently missed your message somehow, sorry about that!

It would definitely be neat to have them in ACE3 itself, although probably best to do it after or with medical rewrite. I think 2 separate categories would make sense, as they are different mods after-all, but as long as UBCs don't happen, I am happy.

**Comment by dedmen** [comment]
If the modules are designed for ACE. Why do you need a ACE medical category if ACE is not loaded?
Because if ACE is loaded then that Faction class will already exist. With the "ACE Medical" displayName. So no reason whatsoever to recreate that class when ACE is loaded. And I don't see a reason to have a ACE category if ACE isn't loaded at all.

**Comment by CreepPork** [comment]
@dedmen The module has two functions, first it was designed to only have ACE medical functions, but after that, it was expanded to have also the vanilla options there as well. So it stayed there in that category and hasn't been moved, yet.

I do agree that this is quite confusing and in my opinion, should be separated into two different modules, one for ACE and one for vanilla depending on what is loaded.
