### ISSUE TITLE
Weaponry Dependencies

### ISSUE THREAD

**Issue by Theassassinzz** [ArmaAchilles/AresModAchillesExpansion#120]
Some weaponry in the vanilla ArmA list is being taken over by Achilles mod. Therefor causing 
Achilles to become a dependency. This isn't a do or die situation but it is frustrating have to edit the
mission.sqm before pushing an update to a server that doesn't require any mods

**Comment by CreepPork** [comment]
The issue with this is - it's a double-edged sword. If I remove, what causes the dependency, then it slows down the Arsenal that uses a side config parameter to increase performance. You can check the comment [here](https://github.com/ArmaAchilles/AresModAchillesExpansion/blob/00d57839f94b02bb57e7d6c17881700d913e0528/%40AresModAchillesExpansion/addons/data_f_ares/config/cfgVehiclesSortingOverrides.hpp#L1).

**Comment by CreepPork** [comment]
Closed in favour of #200.
