### ISSUE TITLE
Revision of The Reinforcement Module I

### ISSUE THREAD

**Issue by oOKexOo** [ArmaAchilles/AresModAchillesExpansion#145]
- [x] Fix: General instabilities... (e.g. #66)
- [x] Change: Search should no longer depend on the module tree, but solely on configs.
- [x] Change: Introduce a cache.
- [x] ~Feature: Customized filling of vehicles (e.g. #17)~ (moved to #213)

**Comment by ArchangelM127** [comment]
A possibly simpler idea would be to add one or two new fields in the Spawn Reinforcements dialog, so the user could specify two or three different (or the same) groups to spawn in the selected vehicle. Any soldiers that don't fit would be auto-deleted, as now. So the user could either spawn several small groups into the same truck, or several full squads to parachute out of a C-130.

**Comment by oOKexOo** [comment]
Don't comment on outdated issues. Either create a new one or comment on the active one. In this particular case the active one is #213.
