### ISSUE TITLE
Multiple modules not working in a dedicated and/or local environment - #155

### ISSUE THREAD

**Issue by JANXOL** [ArmaAchilles/AresModAchillesExpansion#152]
As the title states, the module is not working for me. The dialog window does appear as normal, i can move the slider or select a date and hour. The preview button also works, but accepting the change gives no effect at all. The change weather module and skip time module work fine.

Edit by CreepPork:
Modules not working (checked if fixed), associated with #155 issue:
- [x] Set Date module
- [ ] ~~Destroy Buildings module~~
- [x] Toggle lamps module
- [x] Custom Module code using the JIP mode

**Comment by CreepPork** [comment]
I think I know what has caused the issue and I'll have a look tommorow. Kex did some changes to remote execution and broke a lot of stuff, so that might be the reason.

**Comment by JANXOL** [comment]
Actually, now that you mention remote execution, it also seems that execute code module has some issues. I cannot seem to execute commands such as auto-setting tfar frequencies or nuclear explosion fx (all of those are client-executed by remote exec.

**Comment by CreepPork** [comment]
I had no issues with the execution module. It seemed fine.

**Comment by JANXOL** [comment]
I am certain of it. At last two script i use for a long time stopped working. If it helps, i can post they here when i get to my main pc. No other mods were updated, and the script stopped working after last achilles update

**Comment by CreepPork** [comment]
@JANXOL Can you post your .rpt as everything seems fine and also your scripts could be of use, as I can't replicate the issue.

**Comment by CreepPork** [comment]
Sounds like a locality issue, I'll have a look on a dedi.
Can you also try any other scripts that don't involve mods? It might be just another mod issue (probably not).
Also, I don't think that you should use calling BIS_fnc_MP as the actual execution is handled behind the scenes when you select the type of execution. I think I got that right but @oOKexOo can correct me if I'm wrong.

P.S. BIS_fnc_MP is depreciated, use remoteExec or remoteExecCall.

**Comment by JANXOL** [comment]
I am aware its depreciated and slower, but as I mentioned those scripts survived in this form for a long time. 
Also in this case I;m calling BIS_fnc_MP because some of those are client-side and some are server side (last one). So i am calling server to do his thing and also telling it to execute client-side part for everyone. 
Everything was working untill the last Achilles update.

I will try a script that isn't dependent on mods once I get the chance.

**Comment by CreepPork** [comment]
There are a bunch of errors at the timestamp 21:35:20, regarding the nuke (it's a snip here):
```
21:35:20 Error in expression <andom 360;
_aglz = random 90;
_upposx = _xpos + _dist * (sin _agl) * cos _aglz;
>
21:35:20   Error position: <_xpos + _dist * (sin _agl) * cos _aglz;
>
21:35:20   Error Undefined variable in expression: _xpos
21:35:20 File \rhsafrf\addons\rhs_c_rva\scripts\nuke\fnc_light_effects.sqf [RHS_fnc_ss21_nuke_fx_light], line 18
21:35:20 Error in expression <andom 360;
_aglz = random 90;
_upposx = _xpos + _dist * (sin _agl) * cos _aglz;
>
21:35:20   Error position: <_xpos + _dist * (sin _agl) * cos _aglz;
>
```

**Comment by JANXOL** [comment]
I noticed that. It would appear that the variable "nuke" bound to the object wasn't passed correctly.

**Comment by JANXOL** [comment]
I have actually tried a tiny "script" last time.

`player addAction ["Set radio frequencies", "scripts\radio.sqf","",0,false];`
Executed globally, it was supposed to add an action to every player's scrollwheel menu (regardless of whether the action would actually do anything). It only added an action to me, not to any other players.

`player addAction ["Test", "","",0,false];`
Resulted in the same thing (this action does nothing by design).

**Comment by JANXOL** [comment]
Also, this would be the modernised version of the nuke script. (Still executed on Server)
Same issue as original.

```
{    [(getPos nuke),500,500] remoteExec [_x,0];
	}	foreach [
    		"rhs_fnc_ss21_nuke_fx_smoke",
   		 "rhs_fnc_ss21_nuke_fx_light",
   		 "rhs_fnc_ss21_nuke_fx_shockwave",
    		"rhs_fnc_ss21_nuke_fx_postprocessing"
];

[(getPos nuke),500,500] remoteExecCall ["rhs_fnc_ss21_nuke_fx_damage",2]; 
```

**Comment by CreepPork** [comment]
Yes, I can replicate the issue on a dedicated server.

**Comment by CreepPork** [comment]
For the Execute Module when trying to execute in the Global & JIP mode it doesn't work but when using Global mode it does work.
These below work in Global mode but not in Global and JIP.
```sqf
hint "test";
```
and
```sqf
player addAction ["Test", "","",0,false];
```

_God, @oOKexOo why did you introduce your "safe" remoteExec's *sigh*_

**Comment by JANXOL** [comment]
Global definitely doesn't work. It works only for the one who executes the command (behaves like local), but no other players are affected. For example, if me and one other player were in the server, and I used the 
`player addAction ["Test", "","",0,false];`

The action was added to me, but not the second player. Same for radio freqs, it only set them for me, not the other player.

**Comment by JANXOL** [comment]
I also have a suspicion that binding a a variable and setting it to "public" doesnt actually make it public. Can't check right now,, because I would need a second player, but I suppose it can be tested with hideObejct.

**Comment by CreepPork** [comment]
As I previously stated, the Execute Code module works fine apart from the JIP mode. It does work for me on a dedicated server and the commands are also executed fine for other players. This issue you are experiencing is a fault on your end as I cannot replicate this issue. If you have any mods added apart from Achilles, unload them and try again. Possibly message me on Discord and we can have a closer chat about this.

**Comment by JANXOL** [comment]
I will do some more testing when I get the chance and get to you on discord with some results, then.

**Comment by CreepPork** [comment]
Modules not working (checked if fixed):
- [ ] Set Date module
- [ ] Destroy Buildings module
- [ ] Toggle lamps module
