### ISSUE TITLE
Make group ID changes global

### ISSUE THREAD

**Issue by freghar** [ArmaAchilles/AresModAchillesExpansion#153]
Zeus allows you, on group double-click, to change the group ID (also called callsign) of the group. This change however uses `setGroupId`, not `setGroupIdGlobal`, so any changes are local only to the Zeus player.

This is in `Curator\Addons\ui_f_curator.pbo` defined as
```
class RscAttributeGroupID : RscControlsGroupNoScrollbars {
	onSetFocus = "[_this,""RscAttributeGroupID"",'CuratorCommon'] call (uinamespace getvariable ""BIS_fnc_initCuratorAttribute"")";
        ...
```
which refers to `RscAttributeGroupID` meaning `RscAttributeGroupID.sqf` which is under `ui_f_curator\UI\RscCommon\RscAttributeGroupID.sqf` and contains
```
...
	case "confirmed": {
...
		if (_text != groupID _entity) then {
			_entity setgroupid [_text];
		};
...
```
Changing that `setgroupid` to `setGroupIdGlobal` should do the trick.
Even better, I would recommend removing the condition and doing the `setGroupIdGlobal` always, in case the Zeus client has already "desynced" group ID.

I would personally patch it by overriding just the `onSetFocus` line, but I've seen the `Replacement` directory in Achilles do it a bit differently (copying entire classes it seems), so I'll leave it up to you how to implement this, should you wish to accept this feature request.

Thanks!

**Comment by CreepPork** [comment]
This indeed is a bug and can be replicated on a dedicated server. Using `setGroupIDGlobal` does fix the issue and should, therefore, be used. The group ID only changes for the Curator.
