### ISSUE TITLE
Fastroping waypoint problem without AdvancedRappelling installed on the Zeus client

### ISSUE THREAD

**Issue by Victor9401** [ArmaAchilles/AresModAchillesExpansion#160]
**Arma 3 Version:** `1.72` (stable)
**AresModAchillesExpansion Version:** `0.0.9c`

**Mods:**
```
- CBA_A3
- AresModAchillesExpansion
- AdvancedRappelling
```

**Description:**
- Fast-roping waypoint is not working when AR is not installed on zeus client (works for players as intended)

**Where did the issue occur?**
- Dedicated server

**Comment by CreepPork** [comment]
I've introduced a fix in the a7e66fc commit. This addresses the issue that units were left hanging in the air and left to get killed.

Hopefully, it works as I have not been able to test if it actually works or not.

As for the "partially resolved" tag, I have an idea to somehow maybe make it work without the Curator needing it on their machine to be loaded, but have to figure out a way to do so.

**Comment by Victor9401** [comment]
As I can understand, fix in fn_wpFastrope.sqf isn't needed, because it will cause non reinforcement helis to disappear in mid air, when mowing from wp to wp. I can recommend to replace that wp to `LAND` type with hint message, if that's possible, so it won't cause some strange behavior to zeus spawned helis with flight plans.

**Comment by CreepPork** [comment]
Ah, I see what you mean. I'll get a fix for that.
