### ISSUE TITLE
Deploy countermeasure button bug

### ISSUE THREAD

**Issue by Victor9401** [ArmaAchilles/AresModAchillesExpansion#161]
**Arma 3 Version:** `1.72` (stable)
**AresModAchillesExpansion Version:** `0.0.9c`

**Mods:**
```
- CBA_A3
- AresModAchillesExpansion
```

**Description:**
Use countermeasure button not working on some vehicles:
- V-44 X (No countermeasure available)
- F/A-181 (No countermeasure available)
- Every vehicle with 2+ slots (no message and nothing happens)
- Groups of soldiers in selection (Only first one in selection drops smoke grenade)

It works as intended (shows message about no countermeasures available) if you use all smokes in vehicle with 2+ crew with remote control, and then try to deploy them through zeus interface.

**Where did the issue occur?**
- Dedicated server

**Comment by CreepPork** [comment]
Possibly related to #152 and #155.
