### ISSUE TITLE
fn_setDict and fn_setDictKeyword

### ISSUE THREAD

**Issue by Victor9401** [ArmaAchilles/AresModAchillesExpansion#162]
**AresModAchillesExpansion Version:** `0.1.0` latest

I think, that in `fn_setDict` and `fn_setDictKeyword` there are errors in 
```
_dict_storage = [] call compile format ["Achilles_var_dictStorage_%1;",_dictName];
```
There is no local variable with name `_dictName`.

Don't know if that code is used somewhere.

**Comment by CreepPork** [comment]
Yes, that variable is undefined and also the code isn't used anywhere so that's why it hasn't caused any problems, yet.
But I remember a task list where dicts where mentioned, so it's planned for something :D
