### ISSUE TITLE
Arsenal for side doesn't work

### ISSUE THREAD

**Issue by Victor9401** [ArmaAchilles/AresModAchillesExpansion#167]
Arma 3 Version: 1.72 (stable)
AresModAchillesExpansion Version: 0.0.9c

Mods:

- CBA_A3
- AresModAchillesExpansion

Description:
Created arsenal for side doesn't work in dedicated environment

Where did the issue occur?
Only on dedicated server

**Comment by CreepPork** [comment]
Checked, it's fixed.
