### ISSUE TITLE
Create Mission SQF does not retain enableSimulation attribute of objects.

### ISSUE THREAD

**Issue by mcrow900** [ArmaAchilles/AresModAchillesExpansion#169]
**Arma 3 Version:** Stable Steam Current
**CBA Version:** `3.x.x` Stable Steam Current
**AresModAchillesExpansion Version:** Stable Steam Current

**Mods:**
```
- CBA_A3
- AresModAchillesExpansion
```

**Description:**
Basically have a set-up I created in 3DEN, started, opened up Zeus, added objects to Zeus, and copied mission SQF. I then set-up a blank Altis mission to test, and executed the sqf. When I did all the cans and boxes fell and acted as if simulation was enabled.

**Steps to reproduce:**
-Open blank Altis mission and paste this https://pastebin.com/raw/jpRbQe5R

**Where did the issue occur?**
- Dedicated And Editor (Singleplayer)

**Comment by CreepPork** [comment]
Please fill out the 3 top fields.

**Comment by mcrow900** [comment]
Don't know the version numbers, it's all from Steam stable branch and up-to-date
