### ISSUE TITLE
[Suggestion] Allow reinforcements to fill vehicle with units.

### ISSUE THREAD

**Issue by HexagonCS** [ArmaAchilles/AresModAchillesExpansion#17]
Currently the reinforcement module only spawns the selected squad. It would make it a lot cleaner, faster and easier if you could have a box that may be ticked and doing so will fill the reinforcement vehicle with the selected squad's units.

**Comment by oOKexOo** [comment]
I like your idea. However, I first have to implement an user interface for that purpose. Maybe I can use the same as I intend to implement for ammo boxes.

**Comment by HexagonCS** [comment]
That would be great! :)

**Comment by oOKexOo** [comment]
Closed as duplicate.
Leading ticket is #145.
