### ISSUE TITLE
AI Charging feature request

### ISSUE THREAD

**Issue by Thegamingharibo** [ArmaAchilles/AresModAchillesExpansion#172]
Hi could a feature be added where the AI would charge at you ww1 style or soviet ww2 style for making those chaotic moments in arma 3 zeus? Maybe a button in AI behaviors that said CHARGE!!!! and it had settings for what type of charge, would they shoot at you while charging and how fast they would run or walk at you.

**Comment by CreepPork** [comment]
I might not sure you could make AI actually accomplish this, as they don't even like running in a straight line and charging them seems impossible to me.

**Comment by Thegamingharibo** [comment]
Maybe its possible now with the tac ops dlc with Bohemia saying there adding new scripting systems.
