### ISSUE TITLE
Artillery Module Not working With RHS AFRF "2S3M1"

### ISSUE THREAD

**Issue by Snak3Doc** [ArmaAchilles/AresModAchillesExpansion#176]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.4.1` (stable)
**AresModAchillesExpansion Version:**  `0.0.9c` (stable)

**Mods:**
```
- ACE V3.11.0
- RHS R/B/G V0.4.3.1
- All of them, please!
```

**Description:**
- The 2S3M1 does not work with the Artillery Fire Mission Module

**Steps to reproduce:**
- Place 2S3M1, use the artillery target module to create a target, use the artillery fire mission module to fire on the target, it won't work. Repeat with the RHS USA Palidin it will work.

**Where did the issue occur?**
- Dedicated Windows

**RPT log file:**
- The link, please?

**Comment by CreepPork** [comment]
Please fill out your issue fully. Instructions available [here](https://github.com/ArmaAchilles/AresModAchillesExpansion/wiki/Issue-Template).

**Comment by CreepPork** [comment]
And it does work for me, can you replicate the issue?

**Comment by Snak3Doc** [comment]
I've had the same report from 2 of my Zeus's and replicated it my self. And yea like I said every other artillery peace works fine from rhs, so I'm not sure how it could be a issue outside of rhs/achilles. As for rpt and other requests my steam drive died so you will have to wait a bit for that, I just did it as best I could from memory.

**Comment by CreepPork** [comment]
I cannot replicate the issue, it does fully work. The only point where I think could be the issue is that the unit moves its cannon up very slowly. This we cannot change as it's related to RHS itself.
