### ISSUE TITLE
Breaching script doesn't work for Remote Controlled or "Switch Unit" units

### ISSUE THREAD

**Issue by CreepPork** [ArmaAchilles/AresModAchillesExpansion#178]
The breach door script doesn't work anywhere.

**Comment by CreepPork** [comment]
The script seems to be working fine only issue is that it doesn't want to work for the curator. In all other cases, it works fine.

**Comment by CreepPork** [comment]
Works for the curator if he is a playable character and not a game logic but if he is remote controlling a unit or using the switch unit module, it doesn't work.

**Comment by oOKexOo** [comment]
In essence, the RC module provides features accessible to AI, whereas the "Switch Unit" module includes player features. Hence, I'll try to make it compatible for at least the latter.

**Comment by CreepPork** [comment]
I'm pretty certain that the module worked previously fine.

**Comment by oOKexOo** [comment]
I fixed it for both now in "switchUnitFixes" branch.
