### ISSUE TITLE
Script error in Achilles_fnc_damageBuildings

### ISSUE THREAD

**Issue by shukari** [ArmaAchilles/AresModAchillesExpansion#182]
**Arma 3 Version:** stable
**CBA Version:** stable
**AresModAchillesExpansion Version:** stable

**Mods:**
```
- CBA_A3
- AresModAchillesExpansion
```

**Description:**
```
21:25:06 Error in expression <1: {_building setDamage 0.8};
case 2:
{
_building setDamage 0.5;
_allHitPoints =>
21:25:06   Error position: <_building setDamage 0.5;
_allHitPoints =>
21:25:06   Error Undefined variable in expression: _building
21:25:06 File \achilles\functions_f_achilles\functions\features\fn_damageBuildings.sqf [Achilles_fnc_damageBuildings], line 40
21:25:06 Error in expression <age_type) + ",3])")};
};
{
_building = _x;
_damage_type = [] call _fnc_getDamag>
21:25:06   Error position: <_x;
_damage_type = [] call _fnc_getDamag>
21:25:06   Error Undefined variable in expression: _x
21:25:06 File \achilles\functions_f_achilles\functions\features\fn_damageBuildings.sqf [Achilles_fnc_damageBuildings], line 32
```

[arma3server_x64_2017-11-14_17-47-30.zip](https://github.com/ArmaAchilles/AresModAchillesExpansion/files/1477628/arma3server_x64_2017-11-14_17-47-30.zip)

**Steps to reproduce:**
unknown zeususer, no more info

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**RPT log file:**
[arma3server_x64_2017-11-14_17-47-30.zip](https://github.com/ArmaAchilles/AresModAchillesExpansion/files/1477631/arma3server_x64_2017-11-14_17-47-30.zip)

**Comment by CreepPork** [comment]
Can you reproduce the issue again and where did the issue occur?

**Comment by shukari** [comment]
I have only the log, no more info.
Map was Isla Duala and someone tried to destroy a house i suppose.

**Comment by CreepPork** [comment]
So Achilles and CBA wasn't the only addon running?

I can't replicate the issue, so please do try to replicate the issue on your side.

**Comment by shukari** [comment]
As i said... i cant replicate it... it was in the serverlog and thas all.
