### ISSUE TITLE
[script error] if enableDebugConsole array

### ISSUE THREAD

**Issue by shukari** [ArmaAchilles/AresModAchillesExpansion#187]
**enableDebugConsole with number or array**
https://community.bistudio.com/wiki/Description.ext#enableDebugConsole
https://community.bistudio.com/wiki/Mission_Editor:_Debug_Console_(Arma_3)#Whitelisting_Multiple_Users

**Code snippet**
https://github.com/ArmaAchilles/AresModAchillesExpansion/blob/591559f5e82091ec9a971f0966275b7da0ff30fa/%40AresModAchillesExpansion/addons/ui_f/scripts/RscDisplayAttributes.sqf#L48

**Use**
https://community.bistudio.com/wiki/BIS_fnc_admin
https://community.bistudio.com/wiki/admin (SERVER ONLY)
https://community.bistudio.com/wiki/getMissionConfigValue (instead of missionconfigfile >> "enableDebugConsole")

**Comment by CreepPork** [comment]
Currently broken for other modules that are not used for admin ones e.g. music modules.
