### ISSUE TITLE
Paradrop broken

### ISSUE THREAD

**Issue by callofmarty** [ArmaAchilles/AresModAchillesExpansion#201]
Waypoint broken: will paradrop one or two soldiers or not at all.
Press V for paradrop: will eject all at once, which kills most units instantly. (see picture)

https://steamuserimages-a.akamaihd.net/ugc/921414614511105540/343C1B52ADC0402F02258A222B37D4863A8D0D35/

**Comment by CreepPork** [comment]
Duplicate of #127.

**Comment by CreepPork** [comment]
@callofmarty And you should follow the issue template given to you automatically.
