### ISSUE TITLE
Set date module shows errors as a server host

### ISSUE THREAD

**Issue by Magik4** [ArmaAchilles/AresModAchillesExpansion#205]
**Arma 3 Version:** `1.80` (stable)  
**CBA Version:** `3.5.0` (stable)  
**AresModAchillesExpansion Version:** `0.0.9c` (stable)  

**Mods:**
```
- CBA_A3
- AresModAchillesExpansion
```

**Description:**
- The problem makes clients on your server not experiencing the effect of a fading screen.
- The bug shows some script errors.

**Steps to reproduce:**
- Host a server.
- As Zeus place the Set date module.
- Press OK.

**Where did the issue occur?**
- Self-Hosted Multiplayer

**Additional info:**
- The date seems to change but the time is sometimes not being synchronized (tested on low minute intervals).
- This problem does not occur when you're zeusing as a client on a hosted server.

**Files:**
- [RPT log file](https://gist.github.com/Magik4/3096911ffcac053d9ab86cf9966f3231)

**Comment by CreepPork** [comment]
This should be resolved, but there is a suspension error which means one of the BIS functions may need to be spawned rather than called. #152
