### ISSUE TITLE
Switch unit overrides the unit's glasses.

### ISSUE THREAD

**Issue by Magik4** [ArmaAchilles/AresModAchillesExpansion#209]
**Arma 3 Version:** `1.80` (stable)  
**CBA Version:** `3.5.0` (stable)  
**AresModAchillesExpansion Version:** `0.0.9c` (stable)  

**Mods:**
```
- CBA_A3
- AresModAchillesExpansion
```

**Description:**
- Using Switch unit still overrides an AI character's glasses.

**Steps to reproduce:**
- In the main menu change glasses of your character to, for example, none.
- Now as Zeus place down a unit with glasses.
- Use Switch unit on that unit.
- Turn on the 3rd person view.
- Look how its glasses automagically disappear.

**Where did the issue occur?**
- Self-Hosted Multiplayer,
- Client on Hosted Multiplayer

**Additional info:**
- Reproducibility: always.

**Files:**
- [RPT log file](https://gist.github.com/Magik4/eb16ab214e25dbaa208dffb05f14b10f)

**Comment by CreepPork** [comment]
I'm not sure but I think I resolved some part of this, perhaps I didn't save the glasses but the face and voice should be saved. I need to check it a bit later.
