### ISSUE TITLE
Generic modules get added after use of add/remove objects to curator module

### ISSUE THREAD

**Issue by MaliceGFS** [ArmaAchilles/AresModAchillesExpansion#219]
**Arma 3 Version:** `1.80` (stable)  
**CBA Version:** `3.5.0` (stable)  
**AresModAchillesExpansion Version:** `0.1.0` (dev cb59b6a3de25e24e284fc1b55c57f92aa011697f)  

**Mods:**
```
- CBA_A3
- AresModAchillesExpansion
```

**Description:**
- Generic modules get added when you use the add/remove editable objects to curator module, They also can't be deleted or moved.

![20171228190036_1](https://user-images.githubusercontent.com/26076132/34427183-e88d0e92-ec04-11e7-8cc1-64ad6a902da6.jpg)

**Steps to reproduce:**
- Go into a map in the editor (Singleplayer)
- Place down a unit
- Place the zeus game master module down somewhere
- launch the scenario
- Go into the zeus interface 
- Place down the add/remove editable objects to curator module
- Observer how two generic modules get added in the edit list

**Where did the issue occur?**
- Editor (Singleplayer) 

**RPT log file:**
- [Pastebin](https://pastebin.com/CKxfAecc)

**Comment by CreepPork** [comment]
Do you have debug mode enabled for Achilles?

**Comment by MaliceGFS** [comment]
No, I just took the source off GitHub built it then launched it with default settings. Was I supposed to?

**Comment by CreepPork** [comment]
In-game in CBA options, there is a setting for Achilles debug mode. It enables adding of all items and removes the filters for Add or Remove objects to Zeus module.

**Comment by CreepPork** [comment]
The Ares and Achilles modules show up because you didn't enable unoffical addons in the Game Master module settings. These Ares and Achilles modules are not filtered by the Add or Remove Objects to Zeus module so they appear in-game.

**Comment by MaliceGFS** [comment]
Out of curiosity how would that determine whether or not they show up because it's not like i'm placing them down manually. Are they there as a work around for something if someone does not have unofficial addons enabled in the game master module.

**Comment by CreepPork** [comment]
The modules are there to add Achilles to the enabled addons and make Achilles work. They should only show up if the Game Master module doesn't have Unoffical Addons enabled.
