### ISSUE TITLE
Add/Remove objects to Zeus

### ISSUE THREAD

**Issue by TheNightstalk3r** [ArmaAchilles/AresModAchillesExpansion#231]
**Arma 3 Version:** `1.80` (stable)  
**CBA Version:** `3.5` (stable)  
**AresModAchillesExpansion Version:** `1.0.0` (stable)  

**Mods:**
```
- CBA_A3
- AresModAchillesExpansion
- ZEC
- ACE3
```

**Description:**
Module does not remove any objects unless used with "All objects in mission".

**Steps to reproduce:**
Place down objects, e.g. houses. Use module "Add/Remove objects from Zeus" and set "Remove", "All", "500m" and click OK. Nothing will disappear from Zeus. Now do same thing with "All objects in Mission" and objects/players will disappear from Zeus editable objects.

**Where did the issue occur?**
- Dedicated

**Comment by TheNightstalk3r** [comment]
Same issue adding objects to Zeus, forgot to mention that (also same way to reproduce).

**Comment by CreepPork** [comment]
Fixed in commit ebbe8bd of the [hotfixes](https://github.com/ArmaAchilles/AresModAchillesExpansion/commits/hotfixes) branch
