### ISSUE TITLE
Code execution for units not available

### ISSUE THREAD

**Issue by Zakant** [ArmaAchilles/AresModAchillesExpansion#234]
**Arma 3 Version:** `1.80` (stable)  
**CBA Version:** `3.5.0` (stable)
**AresModAchillesExpansion Version:** `1.0.0` (stable)

**Mods:**
```
- CBA_A3
- AresModAchillesExpansion
- ACE3
```

**Description:**
Code execution window for units is not available with Ares.

**Steps to reproduce:**
- Join a dedicated server (where you are the admin).
- Make sure "Enable DebugConsole" is set to true!
- Login as admin.
- Spawn a unit.
- Open the units attributes and see the missing code execution window.

**Where did the issue occur?**
- Dedicated

**Comment by CreepPork** [comment]
https://github.com/ArmaAchilles/AresModAchillesExpansion/blob/9dbf7c9525e0f24856931fdb235e36cbe8e8e681/%40AresModAchillesExpansion/addons/ui_f/scripts/RscDisplayAttributes.sqf#L48-L59

Under these circumstances, the dialog appears.

**Comment by Zakant** [comment]
Thats right. But `getMissionConfigValue ["enableDebugConsole", 0];` only checks if the config value was set and not if its controlled by a mission parameter. Mission params can be obtained by using `"DebugConsole" call BIS_fnc_getParamValue;` with `0` as disabled and `1` as enabled for (logged in) admins.
One solution would be to simply change [this line]( https://github.com/ArmaAchilles/AresModAchillesExpansion/blob/9dbf7c9525e0f24856931fdb235e36cbe8e8e681/%40AresModAchillesExpansion/addons/ui_f/scripts/RscDisplayAttributes.sqf#L48) to
 ```private _enableDebugConsole = getMissionConfigValue ["enableDebugConsole", "DebugConsole" call BIS_fnc_getParamValue];```
 as `BIS_fnc_getParamValue` returns `0` if not present.

**Comment by oOKexOo** [comment]
Thx for the report, I just replaced that line.
