### ISSUE TITLE
Units can't be rotated when in garrison

### ISSUE THREAD

**Issue by CreepPork** [ArmaAchilles/AresModAchillesExpansion#240]
This is happening when using the Garrison Nearest module. Same behaviour as in the old versions. Unit moves back to old watch position. Seems like the event handler doesn't work.

Turns out it works in certain situations but not reliably. One direction the unit stays watching but the other doesn't and snaps back.

**Comment by oOKexOo** [comment]
I doubt there is not much to do about it. It is an ongoing issue that is hard to deal. I at least just saw that `doWatch` in [`fn_HandleCuratorObjectEdited.sqf`](https://github.com/ArmaAchilles/AresModAchillesExpansion/blob/master/%40AresModAchillesExpansion/addons/ui_f/functions/keyEvents/fn_HandleCuratorObjectEdited.sqf) should be remote executed.

**Comment by oOKexOo** [comment]
Fixed in #278
