### ISSUE TITLE
Suppressive fire tweaks

### ISSUE THREAD

**Issue by CreepPork** [ArmaAchilles/AresModAchillesExpansion#241]
- [x] Talking guns shouldn't be the default option.
- [x] Talking guns don't match the style of other options (all are lowercase and talking guns is sentence case).
- [x] Talking guns should be moved to the bottom of the mode list.
- [x] Talking guns still works for one unit (This doesn't make sense as talking guns is > 1 unit).
- [x] Units keep firing if the suppressive fire module is deleted from the attached unit.
- [x] ~~Add pistols~~
- [ ] Fix vehicles with weapons to the driver turret and other turrets.

**Comment by oOKexOo** [comment]
Agreed, except "talking guns" should be left as default option. It is the most reasonable fire mode of all available ones tbh.

**Comment by CreepPork** [comment]
My opinion is that you should first fire everything at the target and worry about the ammo later.
