### ISSUE TITLE
Custom spawn zone. Like the LZ for reinforcements

### ISSUE THREAD

**Issue by Ghost77788** [ArmaAchilles/AresModAchillesExpansion#245]
Goodday gentleman,

First off i love the work you have and are doing with Ares/Achilles. 
Second i have a question about the implementation of custom modules which stay and can be used as zones like the lz zone for reinforcements.
When i use it as a custom module and use the #include header, i get a error for the logic.
So my question is is there a way around it so i can make custom spawn zones which will stay on the map and can be used for other purposes.
Thank you in advance for your time and keep up the excellent work.

Respectfully,
Ghost

**Comment by CreepPork** [comment]
There is a variable in the scope called `_deleteModuleOnExit`. If you set it to false then the module will not be automatically cleaned up.

**Comment by oOKexOo** [comment]
Btw. it would be helpful if you post your module code and the error message.
