### ISSUE TITLE
Copy/Paste Non-Arsenal Items

### ISSUE THREAD

**Issue by Rectorol** [ArmaAchilles/AresModAchillesExpansion#246]
**Arma 3 Version:** `1.80` (stable)  
**CBA Version:** `3.5.0` (stable)
**AresModAchillesExpansion Version:** `1.0.1` (stable)  

**Mods:**
```
- CBA_A3
- AresModAchillesExpansion
```

**Description:**
- When using Ares Copy/Paste Arsenal you used to be able gather items that were in a supply inventory and populate you them to other supply inventories. With the recent update it only grabs the items that have been checked on as Arsenal instead of all items in a crate.

**Steps to reproduce:**
- Drop a supply crate, vehicle, anything with a inventory and items in there
- Use Arsenal Copy
- Items do not appear that are in the supply crate

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer

**RPT log file:**
- https://gist.github.com/Rectorol/b669f84944760f8647af5437c04222b0

To see more information about this issue template go to our [wiki](https://github.com/ArmaAchilles/AresModAchillesExpansion/wiki/Issue-Template) page.

**Comment by CreepPork** [comment]
Turns out that in the 1.0.0 pre-release builds this feature was perfectly functioning but @oOKexOo removed it for some reason.
