### ISSUE TITLE
Helo gets stuck after AI fast rope

### ISSUE THREAD

**Issue by Eogos** [ArmaAchilles/AresModAchillesExpansion#257]
**Arma 3 Version:** latest stable
**CBA Version:** 3.5
**AresModAchillesExpansion Version:** 1.0.1

**Mods:**
```
- CBA_A3
- AresModAchillesExpansion
```

**Description:**
- When using the "Fast Roping" editor waypoint I've run into a bit of an issue. While the helo will move to the correct position and fast rope the AI out successfully. The helo will then become physically stuck in that location, unable to move no matter how you angle it.

Example: https://imgur.com/a/Se4tp

**Steps to reproduce:**
- Place helo and ai squad inside helo with fast rope waypoint
- Observe as helo flies to position and gets stcuk after AI fast rope out

**Where did the issue occur?**
- Dedicated / Editor (Multiplayer)

**RPT log file:**
- https://gist.github.com/Eogos/5f4b7d6860e161f3547fe73f2a805b5e

**Comment by CreepPork** [comment]
Please replicate the issue fully with no other mods like you have said in the mod list. Your .rpt contains other addons and fast roping would not work if you don't have ACE or Advanced Rappeling loaded.

**Comment by Eogos** [comment]
Sorry completely forgot to modify that from what the template puts in by default. Here is a list of all the mods in that were in use https://gsca3.com/repos/MainOps/ however I'll go ahead and try it with only CBA, Achilles, and ACE loaded in a little bit.

**Comment by Eogos** [comment]
Alright I have absolutely no idea what caused this. I went and tried it with only ACE, CBA, Achilles, and CUP and it worked so I went back and tried removing all the waypoints and placing them down again on the mission I was making and it worked.
