### ISSUE TITLE
Achilles Crashes Dedicated Server (ACE support?)

### ISSUE THREAD

**Issue by DylanSimpkins** [ArmaAchilles/AresModAchillesExpansion#269]
**Arma 3 Version:** `1.80` (stable)  
**CBA Version:** `3.6` (stable)
**AresModAchillesExpansion Version:** `0.0.9c` (stable)  

**Mods:**
```
- AdvancedRappelling
- AdvancedTowing
- cTab
- CUPFull
- DEGA_Parachutes
- FIR_PilotCrewPack_US
- JS_JC_FA18
- mbghouses
- Nimitz
- Project_OPFOR
- ACE (x.x.x - stable)
- task_force_radio
- RHSRU
- RHSUS
- Wake
- ACEX
- A bunch of unit mods (I can give them if needed)
- CBA_A3
- AresModAchillesExpansion
```

**Description:**
Basically, during operations containing 50+ players, we use the Achilles mod. We don't know the specific cause of it, but randomly throughout the operation (probably due to a certain module within Achilles), the server will crash and the Zeus, I, will most likely gain a game crash under "bad_module_info". The best I can really do is give you the RPT file and try to help give you any other information you may need. Our community owner was able to look into my RPT file and find that ACE was the cause of it. I'm not sure if this is 100% correct, but you can check out the RPT.

**Steps to reproduce:**
Unknown.

**Where did the issue occur?**
Dedicated Server Box

**RPT log file:**
https://gist.github.com/DylanSimpkins/a859611ea08a0ff75193efac0b05dcaa

**Comment by CreepPork** [comment]
First things first, you are using an outdated unsupported version of Achilles.

The addon list is quite substantial and it is the first time seeing this error. So it could be quite difficult to set as a Achilles fault. You should take each mod piece by piece (yes, it's going to be painful) to find out the issue.

**Comment by DylanSimpkins** [comment]
I will do some testing with the latest version of Achilles (I was unaware of the newer updates due me using the non-steam version, my fault.) If it persists, I will try to go through every mod.

Thanks.

**Comment by CreepPork** [comment]
I'm closing this issue as I deem it not relevant anymore to Achilles if you encounter any further issues regarding this particular issue feel free to reopen this issue.
