### ISSUE TITLE
Remove side restriction for non-virtual Zeus

### ISSUE THREAD

**Issue by john681611** [ArmaAchilles/AresModAchillesExpansion#60]
When using Zeus as a player using 'Y' to access Zeus. You are limited to support and objectives for your side or Civies. 

Firstly is it possible to do this vanilla without the mod?

If not can this be default for this mod?

**Comment by oOKexOo** [comment]
I just checked the CAS module code. BIS implemented it the way that a non-virtual Zeus can only use factions that are friendly to him. Same with objectives. This restriction makes sense in situations like ZvZ.
Hence, no way to accomplish this without mod.
I can change this behaviour in Achilles ofc.
