### ISSUE TITLE
Reinforcements issue with RHS

### ISSUE THREAD

**Issue by sargken** [ArmaAchilles/AresModAchillesExpansion#66]
21:19:44 Error in expression <t _current_side select _current_faction select _current_category select _comboIn>
21:19:44   Error position: <select _current_category select _comboIn>
21:19:44   Error Zero divisor
21:19:44 File \achilles\ui_f\functions\dialogs\fn_RscDisplayAttributes_Create_Reinforcement.sqf [Achilles_fnc_RscDisplayAttributes_Create_Reinforcement], line 3781
21:19:44 Error in expression <t _current_side select _current_faction select _current_category;

_vehicle_ctrl>
21:19:44   Error position: <select _current_category;

_vehicle_ctrl>
21:19:44   Error Zero divisor
21:19:44 File \achilles\ui_f\functions\dialogs\fn_RscDisplayAttributes_Create_Reinforcement.sqf [Achilles_fnc_RscDisplayAttributes_Create_Reinforcement], line 3756

When you spawn the Us army W they spawn as USMC D and when you Spawn USMC D they spawn USMC W. If you need more info let me know.

**Comment by oOKexOo** [comment]
That module probably contains the lousiest code I've ever produced. A complete revision of the module including new features is planed for 0.0.8.

**Comment by CreepPork** [comment]
May be related, for example if I'm placing down a Syndikat reinforcement helicopter and I choose a Squad its going to spawn a completely different faction, for example, Syndikat helicopter, spawns a Ukraine's Soldiers (from Project OPFOR).

**Comment by oOKexOo** [comment]
Closed as duplicate.
The leading ticket is #145.
