### ISSUE TITLE
Proximity based intel

### ISSUE THREAD

**Issue by Snak3Doc** [ArmaAchilles/AresModAchillesExpansion#74]
Playing around with the intel module and i thought it would be awesome if it was expanded to include laptops, rugged tablets, data terminal (from endgame) ect and rather than being just a scroll wheel action to pick up it could have a proximity based download time (the same one that's in endgame)

Something extra that im not sure is possible is, adding some way for Zeus to reference a .paa in the mission file and add it to an intel item, so it appears in the player's intel tab

**Comment by oOKexOo** [comment]
1) You can add intel to anything you like. You can even place the module on a unit.
2) I can think about proximity based times.
3) It's already possible: [BIS forum](https://forums.bistudio.com/forums/topic/191113-ares-mod-achilles-expansion/?do=findComment&comment=3163939).

Hence, I renamed the ticket to 2).

**Comment by Snak3Doc** [comment]
Oh cool didn't know you could do the other objects and .paa's thanks

**Comment by oOKexOo** [comment]
Closed in favour of #262.
