### ISSUE TITLE
Add Data Link & Radar Emission controls

### ISSUE THREAD

**Issue by JANXOL** [ArmaAchilles/AresModAchillesExpansion#77]
As advised, I am creating a new request. 
1.Would it be possible to add aircraft carrier to zeus interface?
2. Would it be possible to add modules to manage data link on the fly?
3. Would it be possible to add module to force AI radar on/off? AI AA seems to have trouble using radar guided missiles.

**Comment by oOKexOo** [comment]
1) Yeah, I want to provide a module similar to the one for the HMS Proteus.
2/3) Can't tell yet. I have to check out the DLC in more details.

**Comment by JANXOL** [comment]
Have you thought of the 2/3 feasibility? There are definitely options to toggle those things in Eden.

**Comment by oOKexOo** [comment]
Not yet. These features currently don't have a high priority.
