### ISSUE TITLE
Allow setting waypoint completion distance

### ISSUE THREAD

**Issue by freghar** [ArmaAchilles/AresModAchillesExpansion#98]
It would be nice if, when editing a waypoint, the UI would allow setting, ie. via a slider,
https://community.bistudio.com/wiki/waypointCompletionRadius
https://community.bistudio.com/wiki/setWaypointCompletionRadius

This would allow for soldier patrols to go exactly through tight alleys as they are supposed to (when set to a low radius) or allow a helicopter or a tracked ground vehicle to follow multiple waypoints without slowing down before each one (when set to a higher radius).

**Comment by CreepPork** [comment]
@freghar Sort of the same can be accomplished, but with less precision is just to move the waypoint forward and anticipate where the unit will end up. I've been using that method and its worked so far :D

**Comment by CreepPork** [comment]
@freghar Also @oOKexOo  would have to do some stuff with his / Anton dynamic interface, it looks like it doesn't support it.

**Comment by oOKexOo** [comment]
@freghar 
These features are already on the task list #65.
@CreepPork 
I don't have to adjust the dynamic interface, since I'll edit the vanilla attribute window instead.

**Comment by oOKexOo** [comment]
Closed in favour of #131.
